import { PrismaClient, AffiliateCategory } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const IMG = {
  eiffel: "photo-1502602898657-3e91760cbb34", tokyo: "photo-1540959733332-eab4deabeeaf",
  marrakech: "photo-1597212618440-806262de4f6b", colosseum: "photo-1552832230-c0197dd311b5",
  bali: "photo-1537996194471-e657df975ab4", barca: "photo-1583422409516-2895a77efded",
  osaka: "photo-1553413077-190dd305871c", kyoto: "photo-1493976040374-85c8e12f0c0e",
  europe: "photo-1467269204594-9661b134dd2b", asia: "photo-1528360983277-13d401cdc186",
  africa: "photo-1547471080-7cc2caa01a7e", desert: "photo-1533669955142-6a73332af4db",
  beach: "photo-1501785888041-af3ef285b2aa", temple: "photo-1560998086-bb8f9e7b5b0a",
  city: "photo-1464824477268-36a28a1e2487",
};
function img(k: keyof typeof IMG) { return `https://images.unsplash.com/${IMG[k]}?auto=format&fit=crop&w=1200&q=80`; }

interface City {
  name: string; slug: string; country: string; tagline: string;
  overview: string; bestTime: string; getThere: string; transport: string;
  budget: string; safety: string; visa: string; esim: string;
  currency: string; language: string; tz: string;
}

const cities: City[] = [
  // France
  { name:"Nice",slug:"nice",country:"france",tagline:"Azure coastline, pastel old town and panoramic Mediterranean views.",overview:"Nice sits on the dazzling Cote d'Azur where pastel facades climb towards the Baie des Anges. Stroll the Cours Saleya flower market, explore the hilltop Chateau for sunset, then plunge into the turquoise sea. The city blends French art-de-vivre with Italian flair, Provencal markets and the Matisse and Chagall museums.",bestTime:"May to June and September to October for warm weather with fewer crowds.",getThere:"Nice Cote d'Azur Airport (NCE) is 10 min by tram from the centre. Direct trains from Paris (Gare de Lyon, ~5h45) and Milan connect via TGV.",transport:"The free Tramway Line 2 runs along the promenade; local buses, bike-share and TER trains make day trips to Cannes, Antibes and Monaco effortless.",budget:"Three-star hotels EUR 120-200/night; a traditional lunch EUR 15-25; a daily transport pass EUR 6.",safety:"Generally safe; watch for pickpockets on the tram and around the Old Port at night.",visa:"Schengen visa applies; EU/EEA citizens enter freely; check ETIAS before travel.",esim:"Most EU eSIM providers (Airalo, Holafly, Nomad) cover Nice with strong 4G/5G.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Lyon",slug:"lyon",country:"france",tagline:"Gastronomic heart of France with Renaissance lanes and Roman relics.",overview:"Lyon, at the confluence of the Rhone and Saone, is France's undervalued gem. The Renaissance traboules of Vieux Lyon lead to Roman theatres on Fourviere hill, while Presqu'ile dazzles with luxury boutiques and legendary bouchons serving quenelles.",bestTime:"April to June and September to November for mild walking weather.",getThere:"Lyon-Saint-Exupery Airport (LYS) is 30 km away with a Rhonexpress tram (~30 min). Paris is 2h by TGV; direct Eurostar connects London (~2h).",transport:"The TCL metro, tram and bus network is extensive; Velo'v bike-share covers the city; Confluence tram extends south.",budget:"Three-star hotels EUR 100-180/night; a bouchon meal EUR 20-35; a one-day pass EUR 6.",safety:"Very safe; standard city-centre vigilance.",visa:"Schengen rules apply; EU/EEA citizens free entry.",esim:"Excellent 4G/5G from all major French operators and EU eSIMs.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Marseille",slug:"marseille",country:"france",tagline:"Vibrant port city, calanques and sun-drenched Mediterranean alleys.",overview:"Marseille is France's oldest city and a Mediterranean melting pot. The Vieux Port hums with fisherman tales and bouillabaisse aromas; the Panier district climbs through street art and hidden courtyards. The Calanques National Park offers crystal-cove hiking trails.",bestTime:"June to September for warm seas; early autumn is quieter.",getThere:"Marseille Provence Airport (MRS) is 27 km away with shuttle buses. Paris is 3h by TGV; ferries connect to Corsica and North Africa.",transport:"Metro, tram and bus network covers the city well; the navette ferry links the Vieux Port; day boats run to the Calanques.",budget:"Three-star hotels EUR 110-190/night; a bouillabaisse platter EUR 25-40; daily transport EUR 5.",safety:"Take care around Saint-Charles station and northern districts at night; Vieux Port and Panier are lively and safe.",visa:"Schengen visa; EU/EEA free entry.",esim:"Full 4G/5G; most EU eSIMs work reliably along the coast.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Bordeaux",slug:"bordeaux",country:"france",tagline:"Elegant wine capital with gilded mansions and world-class vineyards.",overview:"Bordeaux's graceful 18th-century architecture, shaded quais along the Garonne and world-famous vineyards make it one of France's most elegant cities. The Cite du Vin museum towers over the river; the Chartrons district charms with antique shops and organic cafes.",bestTime:"May to June and September to October; the September harvest brings lively vineyard festivals.",getThere:"Bordeaux-Merignac Airport (BOD) is 15 km west with a tram link. Paris is 2h by TGV.",transport:"The tram network is extensive and scenic; VCub bike-share is popular along the riverfront; walking is best for the UNESCO centre.",budget:"Three-star hotels EUR 110-190/night; a wine-bar tasting EUR 10-20; a gourmet dinner EUR 35-60.",safety:"Very safe; standard city-centre precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent coverage; all major EU eSIMs work well.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Strasbourg",slug:"strasbourg",country:"france",tagline:"Half-French, half-German — timber-framed houses and Christmas markets.",overview:"Strasbourg sits on the Rhine at the French-German border; its medieval Petite France is a fairy-tale of timber-framed houses, waterfalls and canals. The Gothic Cathedrale Notre-Dame dominates the skyline; the European Parliament nearby reminds visitors this is also the seat of European democracy.",bestTime:"December for the magical Christmas market; April to June for riverside walks.",getThere:"Strasbourg Airport (SXB) is 10 km southwest with a bus connection. Paris is 2h15 by TGV; direct trains also serve Frankfurt.",transport:"The compact centre is best walked or cycled; CTS tram and bus network is clean; bikes are available along the Ill river.",budget:"Three-star hotels EUR 100-170/night; a flammekueche lunch EUR 12-18; a Christmas market stroll is free.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Good 4G/5G; EU eSIMs work well across Alsace.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Toulouse",slug:"toulouse",country:"france",tagline:"La Ville Rose — pink brick, space museums and buzzing student life.",overview:"Toulouse glows rose-pink from its distinctive brick architecture and hums with aerospace innovation. The Cite de l'Espace invites families to explore rockets; the Basilique Saint-Sernin anchors one of Europe's finest Romanesque complexes; the Garonne riverside is endlessly walkable.",bestTime:"April to June and September to October for warm, sunny weather.",getThere:"Toulouse-Blagnac Airport (TLS) is 8 km from the centre with a direct metro link. Paris is 1h15 by TGV.",transport:"Metro line A runs east-west and line B north-south; bike-share and riverside tram extensions make getting around easy.",budget:"Three-star hotels EUR 90-160/night; a cassoulet dinner EUR 20-30; transport day pass EUR 5.",safety:"Very safe; standard city-centre vigilance.",visa:"Schengen visa; EU/EEA free entry.",esim:"Full 4G/5G; all EU eSIMs reliable.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Montpellier",slug:"montpellier",country:"france",tagline:"Mediterranean sun, medieval squares and lively university quarters.",overview:"Montpellier balances Mediterranean sunshine with medieval charm in the Ecusson old town. Place de la Comedie, the vast esplanade and the nearby Palavas-les-Flots beaches draw sun-seekers; Antigone's neoclassical quays hint at modern ambition.",bestTime:"May to June and September to October for warm days and beach weather.",getThere:"Montpellier-Mediterranee Airport (MPL) is 8 km southwest with a shuttle bus. Paris is 3h30 by TGV.",transport:"The bus network is comprehensive; the city is compact and very walkable in the old quarter.",budget:"Three-star hotels EUR 90-170/night; a seafood lunch EUR 15-25; beach club day passes EUR 15-30.",safety:"Very safe; standard city-centre precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G along the Languedoc coast.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Cannes",slug:"cannes",country:"france",tagline:"Film-star promenade, limestone cliffs and glitzy festivals.",overview:"Cannes commands the Croisette, a glamourous waterfront boulevard lined with palms, designer boutiques and sandy private beaches. The Palais des Festivals hosts the world's most famous film festival each May; the Ile Sainte-Marguerite offers pine-forested trails.",bestTime:"May for the Film Festival; June to September for beach weather; September remains warm and quieter.",getThere:"Nice Cote d'Azur Airport (NCE) is 30 km away with a regular TER train to Cannes (~25 min). Paris is 5h30 by TGV.",transport:"The free coastal bus and nearby TER stations connect Cannes to Antibes and Nice; ferries run to the Iles de Lerins.",budget:"Three-star hotels EUR 130-220/night (higher in May); a coastal lunch EUR 20-35; ferry to Ile Sainte-Marguerite EUR 17 round-trip.",safety:"Very safe; pickpocketing rare on the Croisette.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable along the Riviera.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Lille",slug:"lille",country:"france",tagline:"Flemish-inspired facades, belfry squares and northern energy.",overview:"Lille pulses with a proud Flemish-Belgian heritage, embodied in the Grand Place's golden belfry and the ornate Vieille Bourse. The modern Euralille district and the vast Palais des Beaux-Arts balance the historic centre; nearby Belgium is a short TGV hop away.",bestTime:"April to June and September to October for mild weather and lively terraces.",getThere:"Lille Lesquin Airport (LIL) is 12 km from the centre with a bus connection. Paris is 1h by TGV; Brussels is 37 min.",transport:"The metro line 1 and 2 cover the city well; bike-share and a compact, walkable centre make exploring easy.",budget:"Three-star hotels EUR 90-160/night; a Flemish-meets-French dinner EUR 25-40; museum pass EUR 15.",safety:"Very safe; standard city-centre vigilance.",visa:"Schengen visa; EU/EEA free entry.",esim:"Good 4G/5G; EU eSIMs work reliably.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  { name:"Nantes",slug:"nantes",country:"france",tagline:"Artful machines, emerald gardens and Loire riverfront.",overview:"Nantes dazzles with the Machines de l'Ile, where mechanical elephants roam the Ile de Nantes. The Chateau des ducs de Bretagne anchors a lively cultural quarter; the Loire a Velo cycle path extends west toward the Atlantic.",bestTime:"May to June and September to October for mild weather and river walks.",getThere:"Nantes Atlantique Airport (NTE) is 8 km southwest with a tram link. Paris is 2h by TGV.",transport:"The tram and bus network is efficient; Bicloo bike-share is among France's best; the Loire a Velo path extends west.",budget:"Three-star hotels EUR 90-160/night; a creperie dinner EUR 15-25; museum pass EUR 14.",safety:"Very safe; standard city-centre precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Full 4G/5G; EU eSIMs reliable.",currency:"Euro (EUR)",language:"French",tz:"CET (UTC+1)" },
  // Japan
  { name:"Tokyo",slug:"tokyo",country:"japan",tagline:"Neon-lit metropolis, temple gardens and culinary precision.",overview:"Tokyo dazzles with neon-lit skyscrapers, serene temple gardens and the world's most refined culinary scene. From the Senso-ji incense smoke in Asakusa to Shibuya's scramble crossing, the Meiji Shrine's forested path and Tsukiji's freshest sushi, Tokyo rewards endless exploration.",bestTime:"March to May for cherry blossoms; September to November for autumn colours and mild weather.",getThere:"Narita (NRT) and Haneda (HND) airports serve Tokyo with global connections. The Narita Express and Keisei Skyliner reach the centre in 60-90 min.",transport:"The metro and JR lines cover the city; the JR Pass covers city-centre travel; buses and taxis supplement.",budget:"Three-star hotels JPY 10,000-18,000/night (~EUR 65-115); a ramen bowl JPY 900-1,200; a sushi dinner JPY 2,000-5,000.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities; simplified screening applies.",esim:"Japan eSIMs (Airalo, Ubigi, Sakura) offer excellent 4G/5G nationwide.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  { name:"Osaka",slug:"osaka",country:"japan",tagline:"Japan's kitchen, neon-lit Dotonbori and castle parks.",overview:"Osaka is Japan's kitchen, where takoyaki sizzle on street corners and Dotonbori's neon canals define the nightscape. Osaka Castle rises from a park moat; Shinsekai's retro towers and the Kuromon market's fresh seafood add flavour; a day trip to Nara or Kyoto is effortless.",bestTime:"March to May for cherry blossoms; September to November for mild weather.",getThere:"Kansai International Airport (KIX) is 50 km south with a Haruka express train (~50 min). Tokyo is 2h30 by Shinkansen; Kyoto is 15 min.",transport:"The metro and bus network is extensive; the Osaka Loop Line connects major sights; the Shinkansen stops at Shin-Osaka.",budget:"Three-star hotels JPY 8,000-15,000/night (~EUR 52-97); a takoyaki set JPY 800-1,200; day pass JPY 700.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities.",esim:"Excellent Japan eSIM coverage in Kansai.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  { name:"Kyoto",slug:"kyoto",country:"japan",tagline:"Temples, gardens and traditional teahouses.",overview:"Kyoto is Japan's cultural heart, with over 2,000 temples and shrines. Kinkaku-ji's golden pavilion, Fushimi Inari's thousands of vermillion torii gates and the Arashiyama bamboo grove define the experience; kaiseki cuisine and geisha districts add refined tradition.",bestTime:"March to May for cherry blossoms; November for autumn foliage at temples.",getThere:"Kyoto Station is the hub; the JR San-in Loop Line and Kintetsu lines serve the city. Tokyo is 2h15 by Shinkansen; Osaka is 15 min.",transport:"Buses cover most temples; the Kyoto City Bus and subway; bikes are the best way to explore the eastern temples.",budget:"Three-star hotels JPY 10,000-18,000/night (~EUR 65-115); a kaiseki dinner JPY 5,000-10,000; temple entry JPY 400-1,000.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities.",esim:"Excellent Japan eSIM coverage in Kansai.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  { name:"Sapporo",slug:"sapporo",country:"japan",tagline:"Snow Festival magic, ramen alley and beer gardens.",overview:"Sapporo comes alive every February when the Snow Festival transforms Odori Park into a luminous wonderland of ice sculptures. The ramen alley, Sapporo Beer Museum and Jozankei Onsen offer classic Hokkaido flavour and nature.",bestTime:"February for the Snow Festival; June to August for lavender farms; December for illuminations.",getThere:"New Chitose Airport (CTS) is 40 km south, connected by the rapid JR train (~40 min). Tokyo is 1h30 by bullet train.",transport:"The subway system is clean and extensive; buses cover outer districts; the JR Pass covers city-centre travel.",budget:"Three-star hotels JPY 10,000-18,000/night (~EUR 65-115); a ramen bowl JPY 900-1,200; a brewery tour JPY 1,000.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities.",esim:"Japan eSIMs (Airalo, Ubigi, Sakura) offer excellent 4G/5G nationwide.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  { name:"Nara",slug:"nara",country:"japan",tagline:"Sacred deer, grand Buddha and ancient temple corridors.",overview:"Nara, Japan's first permanent capital, is a day-trip sanctuary of ancient temples and free-roaming deer. The Todai-ji Daibutsu sits inside the world's largest wooden building; Kasuga Taisha's thousands of stone lanterns create a mystical forest atmosphere.",bestTime:"April for cherry blossoms and deer-friendly weather; November for autumn foliage.",getThere:"Nara is reached via JR or Kintetsu from Osaka (~35-45 min) and Kyoto (~45 min). Nara Station is the hub.",transport:"The city is compact and best explored on foot or by rented bicycle; deer park buses run from the stations.",budget:"Three-star hotels JPY 8,000-15,000/night (~EUR 52-97); a tea and wagashi set JPY 800-1,200; temple grounds free.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities.",esim:"Excellent Japan eSIM coverage in Kansai.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  { name:"Kamakura",slug:"kamakura",country:"japan",tagline:"Great Buddha beneath the waves, coastal paths and shrine trails.",overview:"Kamakura, the medieval shogunal capital, sits along a curved bay framed by forested hills and winding hiking trails. The Great Buddha stands serene under temple canopies; Hase-dera overlooks the sea with a golden Kannon; Yuigahama and Shichirigahama beaches complete the escape.",bestTime:"April for cherry blossoms; October for mild hiking weather.",getThere:"Kamakura is 55 min by JR from Tokyo's Shinjuku or Tokyo Station; the Monorail runs from Ofuna station along the coast.",transport:"The Enoden railway loops along the coast; buses reach temples; the city is very walkable.",budget:"Three-star hotels JPY 10,000-18,000/night (~EUR 65-115); a shirasu-don lunch JPY 1,200-1,800; temple entry JPY 200-400.",safety:"Very safe; standard precautions.",visa:"Visa-free for many Western nationalities.",esim:"Excellent Japan eSIM coverage in Kanto.",currency:"Japanese Yen (JPY)",language:"Japanese",tz:"JST (UTC+9)" },
  // Spain
  { name:"Barcelona",slug:"barcelona",country:"spain",tagline:"Gaudi's architecture, Gaudi's legacy and Mediterranean beach culture.",overview:"Barcelona pulses with Gaudi's fantastical architecture — the Sagrada Familia's forest-like naves and Park Guell's mosaic terraces. The Gothic Quarter's medieval lanes, La Boqueria's market stalls and Barceloneta's beachfront complete the Mediterranean capital.",bestTime:"April to June for mild weather and fewer crowds; September to October for golden light.",getThere:"Barcelona-El Prat Airport (BCN) is 12 km from the centre with a bus and Aerobus connection. Madrid is 2h30 by AVE; Paris is 6h30.",transport:"The metro and bus network is extensive; the Aerobus and Aerrail serve the airport; walking is best in the Gothic Quarter.",budget:"Three-star hotels EUR 100-200/night; a tapas crawl EUR 15-25; Sagrada Familia entry EUR 26.",safety:"Very safe; watch for pickpockets in crowded areas.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Seville",slug:"seville",country:"spain",tagline:"Flamenco courtyards, Alcazar mosaics and orange-scented squares.",overview:"Seville pulses with flamenco, tiled courtyards and the golden Alcazar. The Gothic cathedral houses Columbus's tomb; Plaza de Espana's tiled alcoves frame a calm canal; the Triana district is the soul of flamenco, ceramics and tapas.",bestTime:"March to May for Feria and spring warmth; September to October for flamenco festivals.",getThere:"Seville Airport (SVQ) is 10 km northeast with a bus connection. Madrid is 2h30 by AVE; Lisbon is 3h30.",transport:"The metro covers the centre well; bikes and electric scooters are popular along the Guadalquivir; the city is very walkable.",budget:"Three-star hotels EUR 90-170/night; a tapas crawl EUR 15-25; a flamenco show ticket EUR 15-35.",safety:"Very safe; standard precautions against pickpockets.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable across Andalusia.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Valencia",slug:"valencia",country:"spain",tagline:"City of Arts and Sciences, paella origin and beachfront towers.",overview:"Valencia blends Mediterranean beach with the futuristic City of Arts and Sciences, where Calatrava's whale-like structures rise from the former riverbed. The Gothic Cathedral claims the Holy Grail; the Central Market bursts with saffron and fresh seafood.",bestTime:"April to June for garden festivals; September to October for fewer crowds.",getThere:"Valencia Airport (VLC) is 8 km west with a metro connection. Madrid is 1h45 by AVE; Barcelona is 3h.",transport:"The metro and tram network is extensive; the beach-side tram extends south; the Turia Gardens are perfect for cycling.",budget:"Three-star hotels EUR 80-160/night; a paella dinner EUR 15-30; City of Arts ticket EUR 10-20.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable on the Mediterranean coast.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Malaga",slug:"malaga",country:"spain",tagline:"Alcazabar fortress, tapas bars and Costa del Sol sunshine.",overview:"Malaga basks in 300 days of sunshine with a Roman theatre, an Alcazaba fortress and Picasso's birthplace, all within walking distance of the harbour. The regenerated port area buzzes with restaurants and the new Picasso Museum.",bestTime:"May to June and September to October for beach weather with fewer crowds.",getThere:"Malaga Airport (AGP) is 8 km northeast with excellent connections. Madrid is 2h30 by AVE; Granada is 1h30.",transport:"The metro runs east-west; buses cover the coast; Cercanias trains connect coastal towns; taxis and bikes are abundant.",budget:"Three-star hotels EUR 80-160/night; a tapas crawl EUR 12-20; a beach club day pass EUR 15-25.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable on the Costa del Sol.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Bilbao",slug:"bilbao",country:"spain",tagline:"Guggenheim titanium curves, cider houses and bayfront renewal.",overview:"Bilbao reinvented itself around the Guggenheim Museum's sculptural titanium curves. The old quarter's pintxos bars and cider houses serve Txakoli wine and anchovies; the bayfront esplanade and Artxanda funicular offer panoramic views.",bestTime:"April to June for mild weather; September to October for fewer crowds.",getThere:"Bilbao Airport (BIO) is 12 km north with a bus connection. Madrid is 6h by AVE; Barcelona is 6h30.",transport:"The metro covers the city; the funicular climbs Artxanda; the bayfront loop is walkable; Euskotren trains reach coastal towns.",budget:"Three-star hotels EUR 90-170/night; a pintxos crawl EUR 15-25; Guggenheim entry EUR 16.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in the Basque Country.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Granada",slug:"granada",country:"spain",tagline:"Alhambra palaces, Albaicin lanterns and free tapas tradition.",overview:"Granada is crowned by the Alhambra, the most magnificent palace-fortress in Europe, with its Court of the Lions. The Albaicin's whitewashed lanes and Mirador de San Nicolas deliver the iconic sunset view; Granada's tapas culture means a free pint with every drink.",bestTime:"April to June for spring warmth; October for autumn colours and Sierra Nevada ski season.",getThere:"Granada Airport (GRX) is 15 km west with a bus connection. Madrid is 2h45 by AVE; Malaga is 1h30.",transport:"The single metro line runs east-west; buses cover the Albaicin and Sacromonte hills; the city is best walked.",budget:"Three-star hotels EUR 70-150/night; a tapas crawl EUR 10-20; Alhambra ticket EUR 19.",safety:"Very safe; standard precautions in crowded Albaicin lanes.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Granada.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"Cordoba",slug:"cordoba",country:"spain",tagline:"Mezquita columns, flower patios and Moorish echoes.",overview:"Cordoba's Mezquita, a forest of striped arches and horseshoe columns, is one of the world's great religious buildings. The Patio Festival in May transforms the Jewish Quarter with cascading flowers; the Roman bridge and Calahorra Tower frame the Guadalquivir.",bestTime:"May for the Patio Festival; April and October for mild temperatures.",getThere:"Cordoba Airport (ODB) is 5 km south with a bus connection. Madrid is 45 min by AVE; Seville is 45 min.",transport:"The city centre is compact and very walkable; buses reach the Mezquita; bikes are available.",budget:"Three-star hotels EUR 70-140/night; a salmorejo and flamenquino lunch EUR 12-20; Mezquita entry EUR 13.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Andalusia.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  { name:"San Sebastian",slug:"san-sebastian",country:"spain",tagline:"La Concha crescent, pintxos bars and surf on La Perla.",overview:"San Sebastian's crescent bay of La Concha beach is one of Europe's finest urban beaches, backed by Monte Igueldo and the surf swells of La Perla. The Old Town's pintxos bars compete for visitors with tiny plates of jamon and grilled seafood.",bestTime:"June to September for beach and surf; September to October for the Film Festival.",getThere:"San Sebastian Airport (EAS) is 18 km west with a bus connection. Madrid is 4h by AVE; Bilbao is 1h15.",transport:"The city is compact and walkable; buses run along the bay; the Sanbidera bus connects the harbour.",budget:"Three-star hotels EUR 120-200/night; a pintxos crawl EUR 20-35; beach and surf are free.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in the Basque Country.",currency:"Euro (EUR)",language:"Spanish",tz:"CET (UTC+1)" },
  // Italy
  { name:"Rome",slug:"rome",country:"italy",tagline:"Ancient colosseum, Vatican splendour and eternal-city bustle.",overview:"Rome is the Eternal City, where the Colosseum's arches, the Vatican's Michelangelo ceiling and the Trevi Fountain's baroque drama define millennia of civilisation. The Roman Forum, Trastevere's lantern-lit lanes and the city's legendary carbonara and suppli complete the feast.",bestTime:"April to June for mild weather and fewer crowds; September to October for golden light.",getThere:"Rome Fiumicino (FCO) and Ciampino (CIA) airports serve the city with global connections. Direct trains connect Florence (1h30), Naples (1h10) and Milan (3h).",transport:"The metro, bus and tram network covers the city; walking is best in the historic centre; taxis and ride-hailing supplement.",budget:"Three-star hotels EUR 100-200/night; a carbonara dinner EUR 15-25; Vatican Museums entry EUR 17.",safety:"Very safe; watch for pickpockets in crowded metro and piazzas.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Lazio.",currency:"Euro (EUR)",language:"Italian",tz:"CET (UTC+1)" },
  { name:"Florence",slug:"florence",country:"italy",tagline:"Michelangelo dome, leather markets and Renaissance lanes.",overview:"Florence is the birthplace of the Renaissance, where Michelangelo's David and Brunelleschi's dome dominate a compact centre. The Uffizi Gallery houses Botticelli; the Accademia guards David; the leather markets and Tuscan wine bars along the Arno complete the feast.",bestTime:"April to June for spring warmth; September to October for harvest season and golden light.",getThere:"Florence Airport (FLR) is 5 km northwest with an Athena bus to the centre. Rome is 1h30 by high-speed train; Venice is 2h.",transport:"The city is best walked; buses serve outer neighbourhoods; taxis and scooters are abundant.",budget:"Three-star hotels EUR 100-190/night; a bistecca alla fiorentina dinner EUR 40-70; museum pass EUR 20.",safety:"Very safe; watch for pickpockets in crowded museums.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Tuscany.",currency:"Euro (EUR)",language:"Italian",tz:"CET (UTC+1)" },
  { name:"Venice",slug:"venice",country:"italy",tagline:"Canals, marble palazzi and drifting gondolas at dusk.",overview:"Venice is a surreal city built on islands, where canals replace streets and palaces rise from turquoise water. The Grand Canal's palazzi and the Rialto Bridge define the postcard view; Burano and Murano offer colourful lanes and glass-blowing traditions.",bestTime:"April to June for mild weather; September for golden light and quieter canals.",getThere:"Venice Marco Polo (VCE) is 8 km north with an Alilaguna boat or bus connection. Rome is 3h30 by train; Milan is 2h30.",transport:"Vaporetto boats form the public transit network; walking and gondolas explore the canals; water taxis are faster but pricier.",budget:"Three-star hotels EUR 130-250/night; a cicchetti crawl EUR 15-25; a vaporetto day pass EUR 25.",safety:"Very safe; watch bags on crowded vaporettos.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Veneto.",currency:"Euro (EUR)",language:"Italian",tz:"CET (UTC+1)" },
  { name:"Naples",slug:"naples",country:"italy",tagline:"Pizza birthplace, underground tombs and Vesuvius views.",overview:"Naples is raw, authentic and intoxicating — the birthplace of pizza, where a margherita in a roadside shop tastes better than any Michelin star. The underground Naples tour descends into Greco-Roman tombs; the National Archaeological Museum holds the finest Roman mosaics.",bestTime:"April to June for milder temperatures; September for harvest warmth.",getThere:"Naples Airport (NAP) is 7 km northeast with a bus or Alibus to the centre. Rome is 1h10 by high-speed train; Pompeii is 40 min.",transport:"The metro extends north-south; the Circumvesuviana reaches Pompeii, Sorrento and Oplontis; buses serve the hilly centre.",budget:"Three-star hotels EUR 70-140/night; a true Neapolitan pizza EUR 5-10; underground tour EUR 12.",safety:"Take care in the Spanish Quarter at night; the centro storico and the museum are safe and lively.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Campania.",currency:"Euro (EUR)",language:"Italian",tz:"CET (UTC+1)" },
  { name:"Milan",slug:"milan",country:"italy",tagline:"Duomo spires, fashion quadrants and da Vinci's Last Supper.",overview:"Milan is Italy's fashion capital, where the Gothic Duomo's forest of pinnacles crowns the piazza and the Galleria Vittorio Emanuele II sparkles with luxury boutiques. The Santa Maria delle Grazie convent guards da Vinci's Last Supper; the Navigli canals pulse with aperitivo culture.",bestTime:"April to June for spring warmth and outdoor aperitivo; September to October for golden light.",getThere:"Milan Malpensa (MXP) and Linate (LIN) airports are 40-50 km northwest with Malpensa Express trains. Rome is 3h by high-speed train; Venice is 2h30.",transport:"The metro is Italy's best and covers most attractions; trams and buses fill gaps; the Navigli canal belt is best on foot.",budget:"Three-star hotels EUR 110-200/night; an aperitivo buffet EUR 10-15; Last Supper ticket EUR 15-20.",safety:"Very safe; pickpockets in the metro and Duomo area.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Lombardy.",currency:"Euro (EUR)",language:"Italian",tz:"CET (UTC+1)" },
  // Morocco
  { name:"Marrakech",slug:"marrakech",country:"morocco",tagline:"A walled city of souks, courtyards and rooftop terraces.",overview:"Marrakech pulses with the energy of Djemaa el-Fnaa's storytellers and scent-sellers, surrounding the Koutoubia mosque's lanterns. The Ben Youssef Madrasa's intricate tilework, the Majorelle Garden's cobalt oasis and the Bahia Palace's saharian courtyards define a Moorish fantasy.",bestTime:"March to May and September to October for warm days and fewer crowds.",getThere:"Marrakech Menara Airport (RAK) is 9 km from the centre with a bus connection. Casablanca is 3h by train; Fez is 5h30.",transport:"Petits taxis serve the medina; the new tram line connects the ville nouvelle; walking is essential in the narrow medina lanes.",budget:"Three-star hotels EUR 40-100/night; a traditional tagine dinner EUR 6-12; a hammam ritual EUR 5-10.",safety:"Very safe; guides recommended in the medina to avoid getting lost.",visa:"Most nationalities get a visa on arrival; check specific requirements before travel.",esim:"Maroc Telecom and Orange Morocco eSIMs offer 4G coverage; international eSIMs (Airalo) work in major areas.",currency:"Moroccan Dirham (MAD)",language:"Arabic/Berber/French",tz:"WET (UTC+1)" },
  { name:"Fes",slug:"fes",country:"morocco",tagline:"Medieval medina, tanneries and the world's oldest university.",overview:"Fes el-Bali, a UNESCO-listed medieval medina, is one of the world's largest car-free urban zones. The Bou Inania Madrasa and Al-Qarawiyyin University (founded 859 AD) stand among Islamic architecture's finest achievements. The Chouara tanneries' dye pits offer a sensory spectacle.",bestTime:"March to May and September to October for mild temperatures; winters are cool but lively.",getThere:"Fes-Beni M'Sid Airport (FEZ) is 13 km from the centre with a bus connection. Casablanca is 4h by train; Marrakech is 5h30.",transport:"Petits taxis serve the medina; the new tram line connects the ville nouvelle; walking is essential in the narrow lanes.",budget:"Three-star hotels EUR 40-90/night; a traditional tagine dinner EUR 6-12; a hammam ritual EUR 5-10.",safety:"Very safe; guides recommended in the medina to avoid getting lost.",visa:"Most nationalities get a visa on arrival.",esim:"Orange and Maroc Telecom coverage is decent in the centre; 4G in the valley.",currency:"Moroccan Dirham (MAD)",language:"Arabic/Berber/French",tz:"WET (UTC+1)" },
  { name:"Tangier",slug:"tangier",country:"morocco",tagline:"Strait gateway, Cape Spartel lighthouse and Gibraltar views.",overview:"Tangier perches above the Strait of Gibraltar where the Atlantic meets the Mediterranean. The Grand Socco, the Kasbah Museum and the Caves of Hercules frame a city layered with Spanish, French and Moorish influences. The sunset from Cape Spartel is legendary.",bestTime:"March to May and September to October for mild weather.",getThere:"Tangier Ibn Battouta Airport (TNG) is 12 km from the centre with a bus connection. The ferry from Algeciras (Spain) is 35 min.",transport:"Petits taxis serve the city; the Tanger-Ville train station connects to the interior; the ferry terminal links Spain.",budget:"Three-star hotels EUR 40-100/night; a seafood lunch EUR 8-15; ferry to Spain EUR 35-50.",safety:"Very safe; the medina and Kasbah are lively and secure.",visa:"Many nationalities visa-free or visa-on-arrival.",esim:"Orange and Maroc Telecom coverage is good; EU eSIMs work near the border.",currency:"Moroccan Dirham (MAD)",language:"Arabic/Berber/French",tz:"WET (UTC+1)" },
  { name:"Chefchaouen",slug:"chefchaouen",country:"morocco",tagline:"Blue-washed streets, mountain air and tranquilly painted lanes.",overview:"Chefchaouen's blue-washed streets in the Rif Mountains create one of Morocco's most photographed scenes. The relaxed kasbah and the surrounding valleys offer hiking to wild pools and cedar forests. The town's unhurried pace rewards travellers who linger.",bestTime:"March to May and September to October for hiking weather.",getThere:"The nearest airports are Tangier (TNG) or Fez (FEZ), each 2-3 hours by road. Buses from both cities run regularly.",transport:"The medina is compact and walkable; shared taxis serve the valley; hiking trails begin at the town's edges.",budget:"Three-star hotels EUR 30-80/night; a tagine dinner EUR 5-10; hammam EUR 5.",safety:"Very safe; relaxed, welcoming atmosphere.",visa:"Most nationalities get a visa on arrival.",esim:"Orange and Maroc Telecom coverage is decent in the centre; 4G in the valley.",currency:"Moroccan Dirham (MAD)",language:"Arabic/Berber/French",tz:"WET (UTC+1)" },
  { name:"Essaouira",slug:"essaouira",country:"morocco",tagline:"Wind-powered kite beaches, thuya woodcarvers and ramparts.",overview:"Essaouira's fortified medina, UNESCO-listed and breeze-kissed, is a windswept Atlantic gem. The Skala ramparts and fishing port offer classic sardine-grilling scenes; the thuya-wood workshops and Gnawa music echo the town's cultural heritage.",bestTime:"March to May and September to October for wind and beach weather.",getThere:"Essaouira-Mogador Airport (ESU) is 10 km from the centre with a bus connection. Marrakech is 2h30 by road.",transport:"The medina is compact and walkable; small taxis and beach buses serve the ramparts and port.",budget:"Three-star hotels EUR 40-100/night; a grilled fish lunch EUR 6-12; kitesurfing lesson EUR 40-60.",safety:"Very safe; relaxed Atlantic atmosphere.",visa:"Most nationalities get a visa on arrival.",esim:"Orange and Maroc Telecom coverage is good in the medina; 4G on the ramparts.",currency:"Moroccan Dirham (MAD)",language:"Arabic/Berber/French",tz:"WET (UTC+1)" },
  // USA
  { name:"New York",slug:"new-york",country:"united-states",tagline:"Skyscraper canyons, Central Park and the Broadway heartbeat.",overview:"New York City is the world's ultimate urban theatre: Manhattan's skyscraper canyons, Central Park's green oasis and Broadway's glowing marquees create an endless rhythm of energy. The Statue of Liberty, the MET's encyclopedic collections and the food define every visit.",bestTime:"April to June and September to October for mild weather and fewer crowds.",getThere:"JFK, LGA and EWR airports serve the city with global connections. Amtrak connects Boston (3h30) and Washington DC (3h).",transport:"The subway and buses cover Manhattan and all boroughs; walking is best in Manhattan; yellow taxis supplement.",budget:"Three-star hotels USD 150-300/night; a slice of pizza USD 3-5; a Broadway ticket USD 50-150; museum admission USD 15-30.",safety:"Generally safe; standard city-centre vigilance in crowded areas.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G from Verizon, AT&T, T-Mobile; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"EST (UTC-5)" },
  { name:"San Francisco",slug:"san-francisco",country:"united-states",tagline:"Golden Gate fog, Painted Ladies and steep cable-car hills.",overview:"San Francisco glows with fog-kissed hills, the iconic Golden Gate Bridge and the pastel Painted Ladies of Alamo Square. Fisherman's Wharf, the cable cars and Chinatown — America's oldest — add flavour; the Ferry Building's farmers' market and Silicon Valley complete the edge.",bestTime:"September to November for the warmest, fog-free days.",getThere:"SFO and OAK airports serve the bay with global connections. BART and Muni cover the bay area.",transport:"BART and Muni cover the bay area; cable cars and buses serve iconic routes; walking is best downtown and Fisherman's Wharf.",budget:"Three-star hotels USD 180-350/night; a clam chowder bowl USD 10-15; cable car ride USD 8; museum admission USD 15-25.",safety:"Generally safe; standard precautions in Tenderloin and Union Square.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"PST (UTC-8)" },
  { name:"Los Angeles",slug:"los-angeles",country:"united-states",tagline:"Hollywood sign, Pacific beaches and studio-lined boulevards.",overview:"Los Angeles sprawls across sun-drenched basins where the Hollywood Sign watches over studio-lined boulevards and the Walk of Fame. Venice Beach's boardwalk, the Getty's modernist collection and the food — from Koreatown to the original In-N-Out — define LA's multicultural identity.",bestTime:"May to June and September to October for warm, dry weather.",getThere:"LAX is a major global hub; Burbank, Long Beach and Hollywood Burbank serve secondary routes. Rental cars are the best way to explore.",transport:"Rental cars are best; Metro rail and buses serve the core; ride-hailing is abundant.",budget:"Three-star hotels USD 120-280/night; a gourmet burger USD 15-20; studio tour USD 30-60.",safety:"Generally safe; standard precautions in certain neighbourhoods.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"PST (UTC-8)" },
  { name:"Miami",slug:"miami",country:"united-states",tagline:"Art Deco pastels, Ocean Drive and Latin-Caribbean beats.",overview:"Miami pulses with Latin-Caribbean energy, Art Deco pastels along South Beach's Ocean Drive and the vibrant Calle Ocho of Little Havana. The Wynwood Walls' murals, the Venetian Pool and the Everglades' airboat rides add nature and culture.",bestTime:"March to May for spring warmth; November for Art Basel.",getThere:"Miami International Airport (MIA) is a major Latin-American hub.",transport:"Rental cars and ride-hailing are best; the Metromover and Metrorail serve downtown and Brickell; buses reach South Beach.",budget:"Three-star hotels USD 120-250/night; a Cuban coffee USD 2-3; a Latin dinner USD 20-35.",safety:"Generally safe; standard precautions at night in certain areas.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"EST (UTC-5)" },
  { name:"Las Vegas",slug:"las-vegas",country:"united-states",tagline:"Neon desert Strip, mega-resort pools and night entertainment.",overview:"Las Vegas dazzles with neon mega-resorts, celebrity chef restaurants and round-the-clock entertainment on the iconic Strip. The Hoover Dam and Red Rock Canyon offer desert adventure by day; the Fremont Street Experience pulses with nightlife.",bestTime:"April to May and September to November for warm weather without extreme heat.",getThere:"Harry Reid International Airport (LAS) is 5 miles south with global connections.",transport:"The Strip is walkable; monorail and buses serve the core; rental cars help reach Hoover Dam.",budget:"Three-star hotels USD 60-180/night; a buffet USD 25-50; a show ticket USD 30-100.",safety:"Generally safe; standard precautions on the Strip.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"PST (UTC-8)" },
  { name:"Honolulu",slug:"honolulu",country:"united-states",tagline:"Waikiki surf, volcanic hikes and luau feasts under island skies.",overview:"Honolulu blends island relaxation with Pacific history at Pearl Harbor's USS Arizona Memorial. Waikiki Beach's surf and the Diamond Head hike deliver classic Hawaii; the North Shore's legendary waves and a traditional luau complete the aloha spirit.",bestTime:"April to June and September to November for warm weather.",getThere:"Daniel K. Inouye International Airport (HNL) is a major Pacific hub with direct flights from Asia, Australia and the US mainland.",transport:"TheBus covers Oahu; rental cars are essential for the North Shore; Waikiki is walkable.",budget:"Three-star hotels USD 150-300/night; a poke bowl USD 12-20; a luau USD 80-120.",safety:"Very safe; standard precautions.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"HST (UTC-10)" },
  { name:"New Orleans",slug:"new-orleans",country:"united-states",tagline:"Jazz balconies, wrought-iron galleries and Cajun-spiced evenings.",overview:"New Orleans pulses with live jazz on Frenchmen Street, wrought-iron galleries along the Garden District and Cajun and Creole kitchens. Bourbon Street's energy, Jackson Square's musicians and the above-ground cemeteries create a city unlike anywhere else.",bestTime:"February to May for Mardi Gras; October to November for jazz festivals.",getThere:"Louis Armstrong New Orleans Airport (MSY) is 20 km west with domestic connections.",transport:"The French Quarter is walkable; the streetcar is iconic along St Charles Avenue; buses and taxis supplement.",budget:"Three-star hotels USD 100-220/night; a po'boy sandwich USD 10-15; a Creole dinner USD 25-45.",safety:"Take care in certain French Quarter areas at night.",visa:"ESTA waiver for Visa Waiver Program countries.",esim:"Excellent 4G/5G; US eSIMs widely supported.",currency:"US Dollar (USD)",language:"English",tz:"CST (UTC-6)" },
  // Thailand
  { name:"Bangkok",slug:"bangkok",country:"thailand",tagline:"Temple spires, floating markets and neon-lit Khao San streets.",overview:"Bangkok dazzles with temple spires, floating markets and neon-lit streets. The Grand Palace and Wat Pho's reclining Buddha, the Chatuchak weekend market and the Chao Phraya express boats define the sensory overload; rooftop bars and Michelin-starred street food add modern flair.",bestTime:"November to February for cool, dry season.",getThere:"Suvarnabhumi (BKK) and Don Mueang (DMK) airports serve Bangkok with global connections. The Airport Rail Link reaches the centre.",transport:"The BTS Skytrain and MRT subway cover the core; Chao Phraya express boats; tuk-tuks and taxis supplement.",budget:"Three-star hotels USD 40-100/night; a street-food meal USD 1-3; a rooftop cocktail USD 10-15.",safety:"Generally safe; standard precautions for traffic and scams.",visa:"Visa-free for many nationalities (30 days); eVisa available.",esim:"AIS and TrueMove H eSIMs offer excellent 4G/5G across Bangkok.",currency:"Thai Baht (THB)",language:"Thai",tz:"ICT (UTC+7)" },
  { name:"Chiang Mai",slug:"chiang-mai",country:"thailand",tagline:"Mountain temples, jungle treks and artisan night bazaars.",overview:"Chiang Mai's forested hills and over 300 temples — including Wat Phra That Doi Suthep — offer a spiritual escape. The Sunday Walking Street market overflows with textiles and northern Thai street food; the nearby elephants sanctuaries add ethical adventure.",bestTime:"November to February for cool, dry season; October for the Yi Peng lantern festival.",getThere:"Chiang Mai International Airport (CNX) is 5 km from the centre with domestic connections. Bangkok is 1h20 by flight.",transport:"Songthaews (red trucks) serve temples; tuk-tuks and scooters are abundant; the city is very walkable.",budget:"Three-star hotels USD 30-80/night; a northern Thai curry dinner USD 5-10; temple entry USD 1-2.",safety:"Generally safe; standard precautions for traffic.",visa:"Visa-free for many nationalities (30 days).",esim:"AIS and TrueMove H eSIMs offer excellent 4G/5G in the north.",currency:"Thai Baht (THB)",language:"Thai",tz:"ICT (UTC+7)" },
  { name:"Phuket",slug:"phuket",country:"thailand",tagline:"Andaman beaches, emerald caves and island-hopping piers.",overview:"Phuket is Thailand's largest island, with Andaman beaches, the Phang Nga Bay emerald caves and the Big Buddha overlooking Patong's neon strip. The Old Town's Sino-Portuguese shophouses and Phi Phi day-trips add culture and adventure.",bestTime:"November to April for dry season.",getThere:"Phuket International Airport (HKT) is 30 km north with global connections. Bangkok is 1h20 by flight.",transport:"Songthaews cover the island; airport buses serve the beaches; speedboats connect the islands.",budget:"Three-star hotels USD 60-150/night; a Thai seafood dinner USD 8-15; island-hopping USD 25.",safety:"Generally safe; standard precautions for water sports.",visa:"Visa-free for many nationalities (30 days).",esim:"AIS and TrueMove H eSIMs offer excellent 4G/5G across Phuket.",currency:"Thai Baht (THB)",language:"Thai",tz:"ICT (UTC+7)" },
  // Greece
  { name:"Athens",slug:"athens",country:"greece",tagline:"Acropolis crown, Plaka lanes and tavernas under the Parthenon.",overview:"Athens crowns the Mediterranean with the Acropolis and the Parthenon's enduring marble silhouette. The Plaka's neoclassical lanes tumble towards the Ancient Agora; the National Archaeological Museum houses treasures; the tavernas on Syngrou Avenue serve slow Greek meals.",bestTime:"April to June and September to October for mild weather.",getThere:"Athens International Airport (ATH) is 20 km east with excellent European connections. The metro reaches Syntagma in 40 min.",transport:"The Metro covers the core; buses and trams reach the coast; walking is best in Plaka and Monastiraki.",budget:"Three-star hotels EUR 70-160/night; a taverna dinner EUR 15-25; Acropolis combined ticket EUR 30.",safety:"Very safe; standard precautions in Monastiraki markets.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Attica.",currency:"Euro (EUR)",language:"Greek",tz:"EET (UTC+2)" },
  { name:"Santorini",slug:"santorini",country:"greece",tagline:"Caldera cliffs, whitewashed bowls and sunset-drinks.",overview:"Santorini's caldera cliffs — whitewashed bowls stacked above a flooded volcanic crater — are among the world's most iconic views. The Oia sunset, the red-sand beach of Akrotiri and Assyrtico wine tastings deliver romance and drama.",bestTime:"April to June and September to October for caldera views without peak crowds.",getThere:"Santorini Airport (JTR) is 5 km southeast with Athens connections. The hydrofoil from Piraeus is 4-5 hours.",transport:"Buses connect the caldera villages; ATVs and buses serve the beaches; the caldera views are best savoured on foot.",budget:"Three-star hotels EUR 130-280/night; a seafood dinner EUR 20-35; wine tasting EUR 10-20.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in the Cyclades.",currency:"Euro (EUR)",language:"Greek",tz:"EET (UTC+2)" },
  // Portugal
  { name:"Lisbon",slug:"lisbon",country:"portugal",tagline:"Tram 28 climbs, tiled facades and pastéis de nata at dawn.",overview:"Lisbon's seven hills reward travellers with Tram 28's wobble through Alfama's tiled facades, the São Jorge Castle's Moorish ramparts and the Belém Tower's maritime romance. The pastel de nata custard tarts from Pastéis de Belém and the Miradouros' sunset viewpoints make Lisbon endlessly charming.",bestTime:"March to May and September to October for mild weather.",getThere:"Lisbon Portela Airport (LIS) is 7 km northeast with excellent European connections. The metro reaches the centre in 20 min.",transport:"The iconic Tram 28, metro, buses and funiculars cover the city; ferries to Cacilhas and Cascais are iconic.",budget:"Three-star hotels EUR 70-150/night; a pastéis de nata EUR 1-2; a seafood dinner EUR 15-25.",safety:"Very safe; standard precautions in Alfama at night.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in Portugal.",currency:"Euro (EUR)",language:"Portuguese",tz:"WET (UTC+0)" },
  { name:"Porto",slug:"porto",country:"portugal",tagline:"Ribeira riverfront, port-wine cellars and azulejo-covered lanes.",overview:"Porto's Ribeira riverside is a UNESCO-listed tapestry of azulejo-covered lanes, the Dom Luis I Bridge and the port-wine cellars across the Douro. The Livraria Lello's gothic staircases inspired Harry Potter; the Foz do Douro beaches add coastal elegance.",bestTime:"March to May and September to October for mild weather.",getThere:"Porto Francisco Sa Carneiro Airport (OPO) is 12 km northwest with European connections. The train from Lisbon is 3h.",transport:"The metro, buses and the river cable car serve the city; walking is best in the Ribeira; the Douro Valley is best explored by train.",budget:"Three-star hotels EUR 60-140/night; a francesinha sandwich EUR 8-12; a port-wine tasting EUR 10-20.",safety:"Very safe; standard precautions.",visa:"Schengen visa; EU/EEA free entry.",esim:"Excellent 4G/5G; EU eSIMs reliable in northern Portugal.",currency:"Euro (EUR)",language:"Portuguese",tz:"WET (UTC+0)" },
  // Brazil
  { name:"Rio de Janeiro",slug:"rio-de-janeiro",country:"brazil",tagline:"Sugarloaf cable cars, Copacabana waves and Christ atop Corcovado.",overview:"Rio de Janeiro is a tropical theatre of sugarloaf cable cars, Copacabana's white-and-black wave and Christ the Redeemer atop Corcovado. The Tijuca Forest's waterfalls, the Selaron Steps' mosaics and the churrascarias' rodizio grills add natural and culinary spectacle.",bestTime:"December to March for summer warmth and Carnival; April to June is quieter.",getThere:"Rio de Janeiro International Airport (GIG) is 20 km from the centre with South American connections.",transport:"The metro covers the core; the VLT light rail serves the port; taxis and ride-hailing supplement; the cable cars reach Sugarloaf and Corcovado.",budget:"Three-star hotels USD 70-180/night; a churrascaria dinner USD 20-40; Christ the Redeemer entry USD 25.",safety:"Take standard precautions; avoid certain favelas at night.",visa:"Visa-free for many Western nationalities.",esim:"Claro, Vivo and TIM eSIMs offer excellent 4G/5G in Rio.",currency:"Brazilian Real (BRL)",language:"Portuguese",tz:"BRT (UTC-3)" },
  // Egypt
  { name:"Cairo",slug:"cairo",country:"egypt",tagline:"Pyramid plateau, Khan el-Khalil bazaar and Nile evening feluccas.",overview:"Cairo is the pharaonic heart of the Middle East, where the Pyramids of Giza and the Sphinx rise from the desert plateau. The Egyptian Museum's golden treasures, the Islamic Cairo's mosques and the Khan el-Khalil bazaar's spice stalls create an overwhelming sensory journey.",bestTime:"October to April for milder temperatures; March to May and October are ideal.",getThere:"Cairo International Airport (CAI) is 20 km northeast with connections across Africa, Europe and the Middle East.",transport:"The metro covers the core; taxis and ride-hailing supplement; the Nile ferries connect downtown to Zamalek.",budget:"Three-star hotels USD 40-90/night; a koshari street meal USD 1-3; a Nile dinner cruise USD 10-20.",safety:"Take standard precautions; stay aware in crowded bazaar areas.",visa:"Visa on arrival for most nationalities; eVisa available.",esim:"Orange and Vodafone eSIMs offer 4G in central Cairo.",currency:"Egyptian Pound (EGP)",language:"Arabic",tz:"EET (UTC+2)" },
];

async function main() {
  let n = 0;

  // Regions
  for (const r of [{ name: "Oceania", slug: "oceania", overview: "Sun-drenched islands, reef wonders and cosmopolitan harbours.", type: "REGION", isActive: true }]) {
    await prisma.destination.upsert({ where: { slug: r.slug }, update: { ...r } as any, create: r as any });
    n++;
  }

  // Countries
  const regionIds: Record<string, string> = {};
  for (const r of await prisma.destination.findMany({ where: { type: "REGION" } })) regionIds[r.slug] = r.id;
   for (const c of [{ name: "United States", slug: "united-states", region: "americas", type: "COUNTRY", parentId: regionIds["americas"], isActive: true }, { name: "Canada", slug: "canada", region: "americas", type: "COUNTRY", parentId: regionIds["americas"], isActive: true }, { name: "Mexico", slug: "mexico", region: "americas", type: "COUNTRY", parentId: regionIds["americas"], isActive: true }, { name: "Thailand", slug: "thailand", region: "asia", type: "COUNTRY", parentId: regionIds["asia"], isActive: true }, { name: "Greece", slug: "greece", region: "europe", type: "COUNTRY", parentId: regionIds["europe"], isActive: true }, { name: "Portugal", slug: "portugal", region: "europe", type: "COUNTRY", parentId: regionIds["europe"], isActive: true }, { name: "Egypt", slug: "egypt", region: "middle-east", type: "COUNTRY", parentId: regionIds["middle-east"], isActive: true }, { name: "South Africa", slug: "south-africa", region: "africa", type: "COUNTRY", parentId: regionIds["africa"], isActive: true }, { name: "Brazil", slug: "brazil", region: "americas", type: "COUNTRY", parentId: regionIds["americas"], isActive: true }, { name: "Tanzania", slug: "tanzania", region: "africa", type: "COUNTRY", parentId: regionIds["africa"], isActive: true }, { name: "Kenya", slug: "kenya", region: "africa", type: "COUNTRY", parentId: regionIds["africa"], isActive: true }]) {
    const { region, ...rest } = c;
    const row = await prisma.destination.upsert({ where: { slug: c.slug }, update: { name: c.name, isActive: true } as any, create: { ...rest, type: "COUNTRY", parentId: regionIds[region], isActive: true } as any });
    regionIds[c.slug] = row.id;
    n++;
  }

  // Cities
  const countryIds: Record<string, string> = {};
  for (const c of await prisma.destination.findMany({ where: { type: "COUNTRY" } })) countryIds[c.slug] = c.id;
  for (const c of cities) {
    await prisma.destination.upsert({ where: { slug: c.slug }, update: { name: c.name, isActive: true, tagline: c.tagline, overview: c.overview, bestTimeToVisit: c.bestTime, howToGetThere: c.getThere, transportation: c.transport, budget: c.budget, safety: c.safety, visaInfo: c.visa, esimInfo: c.esim, currency: c.currency, language: c.language, timezone: c.tz } as any, create: { name: c.name, slug: c.slug, tagline: c.tagline, overview: c.overview, bestTimeToVisit: c.bestTime, howToGetThere: c.getThere, transportation: c.transport, budget: c.budget, safety: c.safety, visaInfo: c.visa, esimInfo: c.esim, currency: c.currency, language: c.language, timezone: c.tz, type: "CITY", parentId: countryIds[c.country], isActive: true } as any });
    n++;
  }
  console.log(`Cities upserted: ${n}`);

  // Images
  const CITY_IMAGES: Record<string, string> = {
    nice:"eiffel", lyon:"europe", marseille:"barca", bordeaux:"eiffel", strasbourg:"asia", toulouse:"eiffel",
    montpellier:"eiffel", cannes:"barca", lille:"europe", nantes:"eiffel",
    tokyo:"tokyo", osaka:"osaka", kyoto:"kyoto", sapporo:"colosseum", nara:"kyoto", kamakura:"kyoto",
    barcelona:"barca", seville:"colosseum", valencia:"eiffel", malaga:"barca", bilbao:"osaka", granada:"marrakech", cordoba:"colosseum", "san-sebastian":"barca",
    rome:"colosseum", florence:"colosseum", venice:"eiffel", naples:"colosseum", milan:"barca",
    marrakech:"marrakech", fes:"marrakech", tangier:"marrakech", chefchaouen:"marrakech", essaouira:"marrakech",
    "new-york":"city", "san-francisco":"beach", "los-angeles":"beach", miami:"beach", "las-vegas":"city", honolulu:"beach", "new-orleans":"city",
    bangkok:"temple", "chiang-mai":"asia", phuket:"beach",
    athens:"colosseum", santorini:"eiffel",
    lisbon:"eiffel", porto:"barca",
    "rio-de-janeiro":"beach", cairo:"marrakech",
  };
  let imgCount = 0;
  for (const [slug, key] of Object.entries(CITY_IMAGES)) {
    const url = img(key as keyof typeof IMG);
    const r = await prisma.destination.updateMany({ where: { slug, OR: [{ coverImage: null }, { coverImage: "" }] }, data: { coverImage: url, heroImage: url } });
    imgCount += r.count;
  }
  console.log(`Images assigned to ${imgCount} destinations.`);

  // Affiliate links per new country (raw SQL to handle no composite unique key)
  const affiliateLinks = [
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - United States", destinationText: "United States", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=United+States", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - United States", destinationText: "United States", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=United+States", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Canada", destinationText: "Canada", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Canada", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Canada", destinationText: "Canada", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Canada", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Mexico", destinationText: "Mexico", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Mexico", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Mexico", destinationText: "Mexico", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Mexico", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Thailand", destinationText: "Thailand", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Thailand", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Thailand", destinationText: "Thailand", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Thailand", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Greece", destinationText: "Greece", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Greece", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Greece", destinationText: "Greece", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Greece", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Portugal", destinationText: "Portugal", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Portugal", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Portugal", destinationText: "Portugal", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Portugal", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Egypt", destinationText: "Egypt", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Egypt", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Egypt", destinationText: "Egypt", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Egypt", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - South Africa", destinationText: "South Africa", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=South+Africa", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - South Africa", destinationText: "South Africa", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=South+Africa", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Brazil", destinationText: "Brazil", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Brazil", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Brazil", destinationText: "Brazil", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Brazil", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Tanzania", destinationText: "Tanzania", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Tanzania", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Tanzania", destinationText: "Tanzania", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Tanzania", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
    { partnerName: "Booking.com", category: AffiliateCategory.HOTELS, productName: "Booking.com search - Kenya", destinationText: "Kenya", destinationId: null, targetUrl: "https://www.booking.com/searchresults.en.html?ss=Kenya", dealTitle: "Member prices on stays", priority: 90, utmCampaign: "destination-cities" },
    { partnerName: "GetYourGuide", category: AffiliateCategory.ACTIVITIES, productName: "GetYourGuide - Kenya", destinationText: "Kenya", destinationId: null, targetUrl: "https://www.getyourguide.com/s/?partner_id=K0KEBIE&q=Kenya", dealTitle: "Free cancellation on most tours", priority: 80, utmCampaign: "destination-cities" },
  ];
  let affCount = 0;
  for (const a of affiliateLinks) {
    try {
      await prisma.$executeRaw`INSERT INTO "AffiliateLink" ("id", "partnerName", "category", "productName", "destinationText", "destinationId", "targetUrl", "dealTitle", "promoCode", "active", "priority", "utmCampaign", "createdAt", "updatedAt") VALUES (${crypto.randomUUID()}, ${a.partnerName}, ${a.category}, ${a.productName}, ${a.destinationText}, ${a.destinationId}, ${a.targetUrl}, ${a.dealTitle}, NULL, true, ${a.priority}, ${a.utmCampaign}, NOW(), NOW()) ON CONFLICT DO NOTHING`;
      affCount++;
    } catch (e) { /* duplicate or other error - skip */ }
  }
  console.log(`Affiliate links created/updated: ${affCount}`);
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(async () => { await pool.end(); });
